Add implementation of fs.ReadFile for io/fs.ReadFileFS interface
yalue/merged_fs pull request #4
Opened 2024-02-17 15:42 UTC by purpleidea

- Adds the implementation of ReadFile in two different ways.
- Adds a test to make sure we fulfill the interface and that it
  works.

2024-02-17 15:43 UTC, purpleidea commented
Neat project, thanks! I noticed it wasn't fulfilling this important interface, so I added it. If you like filesystem stuff and want to improve on my failings in https://github.com/purpleidea/mgmt/ which contains an Afero API I'd like to port away from, please let me know!

2024-02-18 01:54 UTC, yalue requested changes

2024-02-18 01:54 UTC, yalue commented on merged_fs_test.go
> +	expectedFiles := []string{
You can probably delete everything starting here (line 119) through line 159.  I understand that you want to call `fstest.TestFS` on the `ReadFileFS` instance, but fortunately the `fstest` package already includes special cases if the target FS implements the interface (for example, see [this line in the fstest code](https://cs.opensource.google/go/go/+/refs/tags/go1.22.0:src/testing/fstest/testfs.go;drc=6dc2d2aa6b9cbab9dc190276cb5a77b4b4a91cd3;l=531)).  Therefore, by implementing the ReadFileFS interface, the existing `TestMergedFS` function's call to `fstest.TestFS` will be sufficient for testing the new functionality.

(Though I still think it's a good idea to explicitly test that `test1.txt` produces the same contents when read through either method.)

2024-02-18 01:54 UTC, yalue commented on merged_fs.go
> +	if true { // safer method in case the stdlib changes
Can we just keep the call to `io.ReadAll(f)` and remove the remaining dead code?

2024-02-18 01:59 UTC, yalue commented
Thanks for the change, with a new test and everything!  I just left a couple comments and I'll be happy to accept it after that.  It looks mgmt is quite an incredible project.  I'll take a look at it, and I do like filesystem stuff (at least in theory), though I doubt I'd be able to contribute much; since my day job means I only have evenings and weekends to free for maintaining my projects on github!

2024-02-22 17:19 UTC, purpleidea commented
Sorry for the delay, I don't have lots of free time. Here's an updated version. Cheers.

2024-02-22 17:49 UTC, merged

2024-02-22 17:51 UTC, yalue commented
Thanks, it's now in tagged version `v1.3.0`.

2024-02-22 17:52 UTC, purpleidea commented
Thank you! HTH

(fwiw :scream: you can fast-forward these simple commits and especially for small projects it will keep your history cleaner)